[package]
name = "simfony"
version = "0.1.0"
authors = ["sanket1729 <sanket1729@gmail.com>"]
license = "CC0-1.0"
homepage = "https://github.com/BlockstreamResearch/simfony/"
repository = "https://github.com/BlockstreamResearch/simfony/"
description = "Rust-like language that compiles to Simplicity bytecode."
edition = "2021"
rust-version = "1.61.0"

[lib]
name = "simfony"
path = "src/lib.rs"

[[bin]]
name = "simc"
path = "src/main.rs"

[dependencies]
base64 = "0.21.2"
hex-conservative = "0.1.1"
pest = "2.1.3"
pest_derive = "2.7.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
simplicity-lang = { git = "https://github.com/BlockstreamResearch/rust-simplicity", rev = "e3866e82001f8b62f0bdcd65dc2d0ec56462d5d7" }
miniscript = "11.0.0"

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["js"] }
